<?php

/*
* Implements hook_block_info()
*/
function aboutioby_block_info() {
  $blocks = array();

  $blocks['ioby_current_stats'] = array(
    'info' => t('ioby Statistics'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}


/*
 * Implements hook_block_view()
 */
function aboutioby_block_view($block_name = '') {
  $block = array();
  if ($block_name == 'ioby_current_stats') {
    $block['subject'] = variable_get('aboutioby_block_title');
    $block['content'] = aboutioby_current_stats();
  }

  return $block;
}

/*
 * Implements hook_theme()
 */
function aboutioby_theme($existing, $type, $theme, $path) {
  return array(
    'aboutioby_display_stats' => array(
      'variables' => array('stats' => NULL),
      'function' => 'aboutioby_display_stats',
    ),
  );
}

/*
 * Implements hook_menu()
 */
function aboutioby_menu() {
  $items = array();
	$items['admin/config/ioby/aboutioby'] = array(
    'title' => 'About ioby',
    'description' => 'Configure the About ioby settings',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('aboutioby_admin_setting'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'aboutioby.admin.inc',
  );

  return $items;
}

/*
 * Implements hook_node_view()
 */
function aboutioby_node_view($node, $view_mode, $langcode) {
  if ($view_mode == 'full' && $node->type == 'about_ioby_section') {
    $menus = menu_get_menus(FALSE);
    $path_parts = explode('/', drupal_get_path_alias());

    switch ($path_parts[0]) {
      case 'about':
        $menu_name = 'menu-about-ioby-menu';
        break;
      case 'idea':
        $menu_name = 'menu-idea';
        break;
      case 'resources':
        $menu_name = 'menu-resources-menu';
        break;
      case 'tips':
        $menu_name = 'menu-tips-menu';
        break;
      case 'campaign-essentials':
        $menu_name = 'menu-campaign-essentials';
        break;
      default:
        return;
    }

    if (!empty($menus[$menu_name])) {
      $trail = array(l(t('Home'), '<front>'));
      $trail[] = l($menus[$menu_name], $path_parts[0]);
      $node->content['navigation'] = menu_tree($menu_name);
      drupal_set_breadcrumb($trail);
      drupal_set_title($menus[$menu_name]);
    }
  }
}

/**
 * Get the current stats for ioby projects
 * @return string
 */
function aboutioby_current_stats() {
  $stats = array();
	for($i = 1; $i <= 15; $i++) {
		$field = 'aboutioby_option' . $i;
		$value = variable_get($field.'_value');
		$label = variable_get($field.'_label');
		if($value && $label) {
			$stats[] = array(
				'value' => $value,
				'label' => $label,
			);
		}
	}
  return theme('aboutioby_display_stats', array('stats' => $stats));
}

/**
 * Markup the list of stats
 * @param array $vars
 * @return string
 */
function aboutioby_display_stats($vars) {
  $stats = $vars['stats'];
  $content = '<ul id="ioby-current-stats">';
  foreach ($stats as $stat) {
    $item = '<div class="stat_num">' . $stat['value']. '</div>';
    $label = '<div class="stat_label">' . $stat['label'] . '</div>';
    $content .= "<li>{$item}{$label}</li>";
  }
  $content .= '</ul>';
  return $content;
}
