<?php
/**
 * @file
 * Install, update and uninstall functions for the Kint module.
 */

/**
 * Implements hook_uninstall().
 *
 * @see hook_uninstall()
 */
function kint_uninstall() {

  // All variables, used by settings
  $variables = array(
    'kint_enabled',
    'kint_displayCalledFrom',
    'kint_maxStrLength',
    'kint_maxLevels',
    'kint_hideSequentialKeys',
    'kint_theme',
  );

  // Remove all listed variables
  foreach($variables as $variable){
    variable_del($variable);
  }
}