<?php
/**
 * @file
 * Code for the Project Form Steps feature.
 */

include_once 'project_form_steps.features.inc';

/**
 * Implements hook_field_access().
 */
function project_form_steps_field_access($op, $field, $entity_type, $entity, $account) {
   $hide_fields = array('field_contact_address', 'field_sponsor_phone',
    'field_project_results', 'field_project_anythingelse',
    'field_demo_age', 'field_demo_ethnicity', 'field_demo_other',
    'field_project_boroughs', 'field_project_contact_phone');

   // Edit operations
   if ($op == 'edit') {
    // Foreach field in array, return false
    foreach ($hide_fields as $hide_field) {
     if ($field['field_name'] == $hide_field) {
       return FALSE;
     }
    }
   }

}
