<?php

/*
 * This is a dummy template design to redirect users to the appropriate project page with the update active
 * It's necessary for links generated by, for example, the RSS feeds for project updates
 */

$new_path = drupal_get_path_alias('node/' . $node->{PROJECT_MEMBERSHIP_FIELD}[LANGUAGE_NONE][0]['target_id']);
$options = array(
    'fragment'=> 'updates/' . $node->nid
  );

drupal_goto($new_path, $options, 301);
