<?php

/**
 * Implementation of hook_menu().
 */
function ioby_faq_menu() {
  $items['admin/config/faqs'] = array(
    'title' => 'FAQs',
    'description' => 'Configure the IOBY FAQ settings',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ioby_faq_admin_setting'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'ioby_faq.admin.inc',
  );
  
  $items[variable_get('ioby_faq_path', 'help')] = array(
    'title' => variable_get('ioby_faq_title', t('Help')),
    //'title callback' => 
    //'title arguments' => 
    'description' => "IOBY's help section",
    'access arguments' => array('access content'),
    'page callback' => 'ioby_faq_page',
    'file' => 'ioby_faq.page.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  
  return $items;
}
 
/**
 * Implementation of hook_theme().
 */
function ioby_faq_theme() {
  
  $theme['ioby_faq_page'] = array(
    'variables'      => array(
      'active_term'  => NULL,
      'view'         => NULL,
      'terms'        => NULL,
      'view_display' => '', 
    ),
    'template' => 'ioby-faq-page',
    'path'     => drupal_get_path('module', 'ioby_faq') . '/theme',
  );
  
  
  return $theme;
}


/**
 * Implements hook_node_view().
 */
function ioby_faq_node_view($node, $build_mode) {
  $args = arg();
  if ($build_mode == 'full' && $node->type=='faq' && count($args)==2 && $args[0]=='node' && $args[1]==$node->nid) {
    $trail = array(
      l(t('Home'), '<front>'),
      l(variable_get('ioby_faq_title', t('Help')), variable_get('ioby_faq_path', 'help')),
    );
    
    // Add the category
    $vocab = taxonomy_vocabulary_load(variable_get('ioby_faq_vocabulary', ''));
    
    if (!empty($vocab)) {
      $meta = entity_metadata_wrapper('node', $node);
      foreach ($meta as $m) {
        if ($m->type()=='taxonomy_term' && $m->vocabulary->vid->value() == $vocab->vid) {
          $tid = $m->tid->value();
        }
      }
      
      if (!empty($tid)) {
        $term = taxonomy_term_load($tid);
        $slug = preg_replace('/\W+/', '-', strtolower($term->name));
        if ($tid == variable_get('ioby_faq_default_category', 15)) {
          $trail[] = l($term->name, variable_get('ioby_faq_path', 'help'));
        }
        else {
          $trail[] = l($term->name, variable_get('ioby_faq_path', 'help') . '/' . $slug);
        }
      }
    }
    
    drupal_set_breadcrumb($trail);
  }
}