<?php
/**
 * @file
 * Code for the Ioby User feature.
 */

include_once 'ioby_user.features.inc';


/**
 * Implements hook_field_access().
 */
function ioby_user_field_access($op, $field, $entity_type, $entity, $account) {

   // If user is done with project (by click on done button)
   if ($field['field_name'] == 'field_steps_complete') {
     return FALSE;
   }
   // if user has submitted idea
  if ($field['field_name'] == 'field_idea_submitted') {
     return FALSE;
   }
}
